[build]
  command = "hugo -s site -d ../dist --minify"
  publish = "dist"
[build.environment]
  HUGO_VERSION = "0.124.1"

[context.deploy-preview]
  command = "hugo -s site -d ../dist --minify --buildDrafts --buildFuture"
